assemblies/fuse-karaf-framework/pom.xml
https://github.com/jboss-fuse/fuse-karaf/commit/a54ba97268a54b8aa3d781602c655a077d204da4
=> Fixed harmfull dependency that prevent correct build after commit:

quickstarts/pom.xml
Add a distribution management section to the quickstarts.   Needed to prevent NEXUS-14460.
=> Add a distribution management section to the quickstarts.   Needed to prevent NEXUS-14460.

quickstarts/cxf/soap/src/test/resources/request.xml
https://issues.jboss.org/browse/ENTESB-7383
Thanks!
=> [ENTESB-7383] fix cxf/soap tests

assemblies/debug/pom.xml, assemblies/fuse-karaf-framework/src/main/filtered-resources/resources/etc/org.ops4j.pax.logging.cfg, assemblies/jboss-fuse-karaf/pom.xml, pom.xml, quickstarts/cxf/secure-soap/pom.xml, quickstarts/pom.xml
Some version alignment to Karaf 4.2.0-SNAPSHOT + logging improvements
=> Ggrzybek changes

quickstarts/camel/camel-odata/README.md, quickstarts/camel/camel-odata/pom.xml, quickstarts/camel/camel-odata/src/main/java/org/apache/camel/example/olingo4/blueprint/Olingo4TestConfiguration.java, quickstarts/camel/camel-odata/src/main/resources/OSGI-INF/blueprint/odata.xml, quickstarts/camel/camel-odata/src/main/resources/data/book1.json, quickstarts/camel/camel-odata/src/main/resources/data/book2.json, quickstarts/camel/camel-odata/src/main/resources/data/book3.json, quickstarts/camel/camel-odata/src/main/resources/data/book4.json, quickstarts/camel/camel-odata/src/main/resources/data/book5.json, quickstarts/camel/camel-odata/src/main/resources/data/person1.json, quickstarts/camel/camel-odata/src/main/resources/data/person2json
https://issues.jboss.org/browse/ENTESB-7066
Thanks!
=> [ENTESB-7066] Update camel-odata quickstart to use camel-odata4

assemblies/jboss-fuse-karaf/pom.xml
https://issues.jboss.org/browse/ENTESB-6715
=> ENTESB-6715 Blacklist features for deprecated Camel components

assemblies/fuse-karaf-framework/src/main/resources/resources/etc/jolokia-access.xml, assemblies/jboss-fuse-karaf/src/main/resources/assembly/etc/jolokia-access.xml
https://issues.jboss.org/browse/ENTESB-5676
=> ENTESB-5676 - Lock down Jolokia by default in Fuse standalone

assemblies/jboss-fuse-karaf/pom.xml, pom.xml
https://issues.jboss.org/browse/ENTESB-7579
Adding the camel-sap feature as a profile option, align karaf/camel-sap/karaf with most recent pipeline build.
=> ENTESB-7579 Add support for fuse-components camel-sap component on Karaf

pom.xml
Change undertow version to 1.4.18-SP2-redhat-1
=> Change undertow version to 1.4.18-SP2-redhat-1

pom.xml
Reverts jboss-fuse/fuse-karaf#95
=> Revert "[ENTESB-7868] Upgrade Undertow to version 1.4.18.SP5-redhat-1"

assemblies/fuse-karaf-framework/src/main/feature/feature.xml, assemblies/fuse-karaf/pom.xml, pom.xml
https://issues.jboss.org/browse/ENTESB-7805
Thanks!
=> [ENTESB-7805] add camel-activemq to distribution

pom.xml
=> Upgrade undertow to SP5.

pom.xml
https://issues.jboss.org/browse/ENTESB-7957
=> ENTESB-7957 Add productised artemis client version into Karaf bom

pom.xml
This reverts commit 750981e3cf88b0501d19846a23a1fa5002b1355f.
=> Revert "[ENTESB-7945] Upgrade Spring to version 4.3.16.RELEASE"

quickstarts/camel/camel-hl7/src/main/resources/OSGI-INF/blueprint/hl7.xml
https://issues.jboss.org/browse/ENTESB-7879
Thanks!
=> [ENTESB-7879] remove file locking strategy from hl7 quickstart

quickstarts/camel/camel-jms/README.md
https://issues.jboss.org/browse/ENTESB-7765
Thanks!
=> [ENTESB-7765] install pax-jms-artemis for camel-jms quickstart

pom.xml
Need to import for spring bom.
=> Add missing dependencies - there are already versions for these artifacts

assemblies/fuse-karaf/pom.xml
https://issues.jboss.org/browse/ENTESB-8072
Thanks!
=> [ENTESB-8072] blacklist instance feature

assemblies/debug/pom.xml, assemblies/fuse-karaf/pom.xml, assemblies/fuse-karaf/src/license/licenses.xml, pom.xml, quickstarts/camel/camel-jms/README.md, quickstarts/persistence/camel-xa/pom.xml, quickstarts/persistence/camel-xa/src/main/blueprint/connection-factory.xml, quickstarts/persistence/camel-xa/src/main/blueprint/xa-datasource.xml, quickstarts/persistence/camel-xa/src/main/java/org/jboss/fuse/quickstarts/beginner/camel/xa/DbMessage.java, quickstarts/persistence/camel-xa/src/main/java/org/jboss/fuse/quickstarts/beginner/camel/xa/ToDbMessageProcessor.java, quickstarts/persistence/camel-xa/src/main/resources/META-INF/persistence.xml, quickstarts/persistence/camel-xa/src/main/resources/OSGI-INF/blueprint/eip.xml, quickstarts/persistence/camel-xa/src/main/resources/OSGI-INF/blueprint/xaTransactionJmsFuse.xml, quickstarts/persistence/databases/blueprints/postgresql-manual.xml, quickstarts/persistence/manual/src/main/asciidoc/02-jdbc.adoc, quickstarts/persistence/manual/src/main/asciidoc/06-connection-factories.adoc, quickstarts/persistence/pom.xml, quickstarts/persistence/readme.adoc
Merge changes from master to 7.1.x branch
=> Merge changes from master to 7.1.x branch

pom.xml
https://issues.jboss.org/browse/ENTESB-8045
=> ENTESB-8045 Upgrade to using spring framework 4.3.16.RELEASE consistently

pom.xml
https://issues.jboss.org/browse/ENTESB-8477
=> ENTESB-8477 Change slf4j version

pom.xml
https://issues.jboss.org/browse/ENTESB-8672
=> Upgrade undertow to SP7

README.adoc
Fixed link to Fuse documentation
=> Fixed link to Fuse documentation

quickstarts/beginner/camel-cbr/README.md, quickstarts/beginner/camel-eips/README.md, quickstarts/beginner/camel-errorhandler/README.md, quickstarts/camel/camel-jms/README.md, quickstarts/custom/README.md, quickstarts/cxf/rest/README.md, quickstarts/cxf/secure-rest/README.md, quickstarts/cxf/secure-soap/README.md, quickstarts/cxf/soap/README.md
https://issues.jboss.org/browse/ENTESB-7783
=> ENTESB-7783 Change READMEs to use new doc URL

quickstarts/camel/camel-salesforce/README.md
https://issues.jboss.org/browse/ENTESB-8223
=> ENTESB-8223 Removed documentation TODO

quickstarts/README.md
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Fix link to Camel folder

quickstarts/persistence/readme.adoc
=> [ENTESB-9700] Use parameterized versions in quickstarts/persistence/readme.adoc

assemblies/fuse-karaf-framework/src/main/feature/feature.xml, assemblies/fuse-karaf/pom.xml, pom.xml
Grzegorz - I *think* these are the reverts needed but please check
=> Revert of ENTESB-9638
